# Generated by Django 3.2.5 on 2021-08-02 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=200)),
                ('account_no', models.CharField(max_length=200)),
                ('bank_name', models.CharField(max_length=200)),
                ('ifsc', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='accountent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountet_id', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('qualification', models.CharField(max_length=200)),
                ('experience', models.CharField(max_length=200)),
                ('e_mail', models.CharField(max_length=200)),
                ('mobile_no', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='audit_request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm_id', models.CharField(max_length=200)),
                ('request_id', models.CharField(max_length=200)),
                ('audit_type', models.CharField(max_length=200)),
                ('request_status', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='audit_types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_id', models.CharField(max_length=200)),
                ('audit_type', models.CharField(max_length=200)),
                ('audit_month', models.CharField(max_length=200)),
                ('start_date', models.CharField(max_length=200)),
                ('end_date', models.CharField(max_length=200)),
                ('fees', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='client_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=200)),
                ('client_name', models.CharField(max_length=200)),
                ('pan', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=200)),
                ('email_id', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('aadhar_no', models.CharField(max_length=200)),
                ('start_date', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='client_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=200)),
                ('client_type', models.CharField(max_length=200)),
                ('pan', models.CharField(max_length=200)),
                ('license_number', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='document_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=200)),
                ('document_id', models.CharField(max_length=200)),
                ('document_name', models.CharField(max_length=200)),
                ('uplaod_date', models.CharField(max_length=200)),
                ('url', models.FileField(upload_to='documents/')),
            ],
        ),
        migrations.CreateModel(
            name='filing_date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filing_id', models.CharField(max_length=200)),
                ('filing_type', models.CharField(max_length=200)),
                ('start_date', models.CharField(max_length=200)),
                ('end_date', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='firm_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm_id', models.CharField(max_length=200)),
                ('firm_name', models.CharField(max_length=200)),
                ('client_id', models.CharField(max_length=200)),
                ('website', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('cin', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='intimation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=200)),
                ('intimation_type', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('details', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='userregistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('mobilenumber', models.CharField(max_length=200)),
            ],
        ),
    ]
